trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployStage
  jobs:
  - job: BuildAndContainerize
    displayName: 'Build and Containerize'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.13.0'
      displayName: 'Install Node.js'
      
    - task: CmdLine@2
      displayName: 'npm install and build'
      inputs:
        script: |
          npm install
          npm install -g @angular/cli@12.2.18
          ng build
          npm -version
          npm --version 
          
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: 'saishadow5473/web-docker'
        tags: 'latest,$(Build.BuildId)'
        
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: 'push'
        containerRegistry: 'docker'
        repository: 'saishadow5473/web-docker'
        tags: 'latest,$(Build.BuildId)'
        pushImage: true

