trigger:
- none
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployStage
  jobs:
  - job: BuildAndContainerize
    displayName: 'Build and Containerize'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.13.0'
      displayName: 'Install Node.js'
      
    - task: CmdLine@2
      displayName: 'npm install and build'
      inputs:
        script: |
          npm install
          npm install -g @angular/cli@12.2.18
          ng build
          npm -version
          npm --version 
          
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to your Dockerfile
        tags: 'docker.io/saishadow5473/docker:$(Build.BuildId)'
        
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: 'push'
        containerRegistry: 'docker'  # Reference to your Docker Hub service connection
        repository: 'saishadow5473/docker'
        tags: 'latest,$(Build.BuildId)'
        pushImage: true  # Ensure this is set to true for private repositories
        
  - job: Deploy
    displayName: 'Deploy to Docker Hub'
    dependsOn:
    - BuildAndContainerize
    steps:
    - task: Docker@2
      displayName: 'Run Docker Container'
      inputs:
        command: 'run'
        containerRegistry: 'docker'  # Reference to your Docker Hub service connection
        repository: 'saishadow5473/docker'
        tags: 'latest'
        ports: '80:80'  # Adjust ports as needed
