trigger:
- none
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployStage
  jobs:
  - job: BuildAndContainerize
    displayName: 'Build and Containerize'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.13.0'
      displayName: 'Install Node.js'
      
    - task: CmdLine@2
      displayName: 'npm install and build'
      inputs:
        script: |
          npm install
          npm install -g @angular/cli@12.2.18
          ng build
          npm -version
          npm --version 
          
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to your Dockerfile
        repository: 'saishadow5473/web-docker'  # Specify your Docker Hub repository
        tags: 'latest,$(Build.BuildId)' 
        
    - script: |
        # List Docker images
        docker images
  #       docker tag 8c99eab4b4d6 saishadow5473/web-docker:latest
  #       docker login -u saishadow5473 -p @vengeR123
  #       docker push 8c99eab4b4d6 saishadow5473/web-docker:latest
  #     displayName: 'List Docker Images'
        
    
        
  # - job: Deploy
  #   displayName: 'Deploy to Docker Hub'
  #   dependsOn:
  #   - BuildAndContainerize
  #   steps:
  #   - task: Docker@2
  #     displayName: 'Run Docker Container'
  #     inputs:
  #       command: 'run'
  #       containerRegistry: 'docker'  # Reference to your Docker Hub service connection
  #       repository: 'saishadow5473/web-docker'
  #       tags: 'latest'
  #       ports: '80:80'  # Adjust ports as needed
